FROM node:26-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

FROM node:26-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app .

CMD ["npm", "start"]
